# see https://github.com/sasstools/sass-lint/tree/master/docs/rules

files:
  include: 'assets/sass/**/*.scss'
options:
  formatter: stylish
  merge-default-rules: true
rules:
  mixin-name-format:
    - 1
    -
      convention: camelcase
  placeholder-in-extend: 0
  no-important: 0
  no-vendor-prefixes: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  class-name-format:
    - 1
    -
      convention: hyphenatedbem
  property-sort-order:
    - 1
    -
      order: smacss
  final-newline: 1
