language: python
python: 2.7
install: "pip install Lektor"
script: "lektor build"
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
addons:
  ssh_known_hosts:
    - asso-pea.ch:2202
deploy:
  provider: script
  script: "lektor deploy production"
  on:
    branch: master
