---
# Name of your project, will also be the vagrant box name
project_name: "mois-vegane"

# Main hostname through which the vagrant box will be accessible
hostname: "mois-vegane.lo"
# Alternative hostnames through which you want to access the vagrant box
hostnames: []

# Ports you want forwared to your host. See https://www.vagrantup.com/docs/networking/forwarded_ports.html
# for details.
forwarded_ports: {
    "80": "8080",    # HTTP
    "443": "8443",   # HTTPS
    "3000": "3000",  # BrowserSync default port
}

# By default Vagrant managed different IPs for all boxes. But you can force it
# here if you want. WARNING, this parameter will not guarantee that your box
# will be accessible at this IP depending on your network configuration or
# provider choice.
# box_ip: "10.10.10.10"

# Root directory of your project for the webserver and other purposes
root_directory: "/vagrant/"
pip_requirements: "requirements.txt"

# If you want to use ubuntu instead of debian (or any other box),
# uncomment this. You can also replace "base" with "php7", if you need
# php7 (with fpm and nginx) anyway.
box_name: "drifter/stretch64-base"
box_url: "https://vagrantbox-public.liip.ch/drifter-stretch64-base.json"
